{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Quickcredit",
    "description" : "An online lending platform that provides short term soft loans to individuals",
    "contact" : {
      "email" : "mnzroger@gmail.com"
    },
    "version" : "1.0"
  },
  "servers" : [ {
    "url" : "http://localhost:1200/api/v1"
  } ],
  "paths" : {
    "/auth/signup" : {
      "post" : {
        "summary" : "User account creation",
        "description" : "Create new user account by passing in (firstName, lastName, email, password), Content-Type should be (x-www-form-urlencoded)",
        "operationId" : "Signup",
        "parameters" : [ {
          "name" : "Content-Type",
          "in" : "header",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "$ref" : "#/components/schemas/signupBody",
            "type" : "string",
            "example" : "application/x-www-form-urlencoded"
          }
        } 
        ],
        "requestBody" : {
          "content" : {
            "application/x-www-form-urlencoded" : {
              "schema" : {
                "$ref" : "#/components/schemas/signupBody"
              }
            }
          },
          "required" : false
        },
        "responses" : {
          "200" : {
            "description": "User account created successfull",
            "headers" : {
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "keep-alive"
                  }
                }
              },
              "Content-Length" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : 508
                  }
                }
              },
              "Content-Type" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "application/json; charset=utf-8"
                  }
                }
              },
              "date" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "2019-04-12 12:23:11"
                  }
                }
              },
              "x-powered-by" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Express"
                  }
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  
                },
                "example" : {
                  "status" : 201,
                  "data" : {
                    "id" : 1,
                    "token" : "df7gd8gd5dhdd9d7f6as",
                    "firstName" : "Roger",
                    "lastName" : "Manzi",
                    "email" : "mnzroger@gmail.com",
                    "password" : "abc@123",
                    "status" : "unverified",
                    "isAdmin" : false,
                    "createdOn" : "2019-05-12"
                  }
                }
              }
            }
          }
        },
        "deprecated" : false
      }
    },
    "/auth/signin" : {
      "post" : {
        "summary" : "User Signin",
        "description" : "Sign in with valid credentials into the request signupBody, Content-Type should be (x-www-form-urlencoded).",
        "operationId" : "Signin",
        "parameters" : [ {
          "name" : "Content-Type",
          "in" : "header",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "example" : "application/x-www-form-urlencoded"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/x-www-form-urlencoded" : {
              "schema" : {
                "$ref" : "#/components/schemas/signinBody"
              }
            }
          },
          "required" : false
        },
        "responses" : {
          "200" : {
            "headers" : {
              "access-control-allow-origin" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "*"
                  }
                }
              },
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "keep-alive"
                  }
                }
              },
              "Content-Length" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : 72
                  }
                }
              },
              "Content-Type" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "application/json; charset=utf-8"
                  }
                }
              },
              "date" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Sat, 11 May 2019 09:59:49 GMT"
                  }
                }
              },
              "etag" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "W/'48-3LmcpBT06+HMmIoM3mOFCcoGhtU'"
                  }
                }
              },
              "x-powered-by" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Express"
                  }
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  
                },
                "example" : {
                  "status" : 200,
                  "data" : {
                    "id" : 1,
                    "token" : "Kcsf87dfD243Werkrs",
                    "firstName" : "Roger",
                    "lastName" : "Manzi",
                    "email" : "mnzroger@gmail.com",
                    "password" : "123@abc",
                    "status" : "unverified",
                    "isAdmin" : false,
                    "createdOn" : "2019-02-12"
                  }
                }
              }
            }
          }
        },
        "deprecated" : false
      }
    },
    "/loans" : {
      "get" : {
        "summary" : "Get loan applications",
        "description" : "Get all loan applications",
        "operationId" : "GetLoanApplications",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "headers" : {
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "keep-alive"
                  }
                }
              },
              "Content-Length" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : 450
                  }
                }
              },
              "Content-Type" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "application/json; charset=utf-8"
                  }
                }
              },
              "date" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Sat, 11 May 2019 09:59:49 GMT"
                  }
                }
              },
              "x-powered-by" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Express"
                  }
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  
                },
                "example" : {
                  "status" : 200,
                  "data" : [ {
                    "id": 1,
                    "user": "manziroger@quickcredit.com",
                    "createdOn": "2019-04-11",
                    "status": "pending",
                    "repaid": false,
                    "tenor": 6,
                    "amount": 1200,
                    "paymentInstallment": 210,
                    "balance": 1050,
                    "Interest": 60
                } ]
                }
              }
            }
          }
        },
        "deprecated" : false
      },
      "post" : {
        "summary" : "Creating a loan application",
        "description" : "Create loan application, user(email) is obtained from the authorization header value(token) by decodeing the header value. Pass Tenor(Interger <= 12) and Loan amount(Float <= Loan Type maximum amount)",
        "operationId" : "CreateLoanApplication",
        "parameters" : [ {
          "name" : "Content-Type",
          "in" : "header",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "example" : "application/x-www-form-urlencoded"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/x-www-form-urlencoded" : {
              "schema" : {
                "$ref" : "#/components/schemas/loanApplicationBody"
              }
            }
          },
          "required" : false
        },
        "responses" : {
          "201" : {
            "headers" : {
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "keep-alive"
                  }
                }
              },
              "Content-Length" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : 267
                  }
                }
              },
              "Content-Type" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "application/json; charset=utf-8"
                  }
                }
              },
              "date" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Mon, 29 Apr 2019 14:45:53 GMT"
                  }
                }
              },
              "x-powered-by" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Express"
                  }
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  
                },
                "example" : {
                  "status" : 201,
                  "Created" : true,
                  "data" : {
                    "id" : 1,
                    "user" : "manziroger@gmail.com",
                    "createdOn" : "Mon, 29 Apr 2019 14:45:53 GMT",
                    "status" : "pending",
                    "tenor": 6,
                    "amount" : 1200,
                    "interest" : 60,
                    "repaid" : false,
                    "paymentInstallment" : 210,
                    "balance" : 1260
                  }
                }
              }
            }
          }
        },
        "deprecated" : false
      }
    },
    "/loans/1" : {
      "get" : {
        "summary" : "Retrieve specific loan application",
        "description" : "Get Loan application by ID passing it as a parameter in the URL",
        "operationId" : "GetSpecificLoanApplication",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "headers" : {
              "access-control-allow-origin" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "*"
                  }
                }
              },
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "keep-alive"
                  }
                }
              },
              "Content-Length" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : 250
                  }
                }
              },
              "Content-Type" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "application/json; charset=utf-8"
                  }
                }
              },
              "date" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Mon, 29 Apr 2019 14:57:29 GMT"
                  }
                }
              },
              "etag" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "W/\"fa-tJjfMPMMwcgzydCbx7OWVy+auso\""
                  }
                }
              },
              "x-powered-by" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Express"
                  }
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  
                },
                "example" : {
                  "status" : 201,
                  "data" : {
                    "id": 1,
                    "user": "manziroger@quickcredit.com",
                    "createdOn": "2019-04-11",
                    "status": "pending",
                    "repaid": false,
                    "tenor": 6,
                    "amount": 1200,
                    "paymentInstallment": 210,
                    "balance": 1050,
                    "Interest": 60
                }
                }
              }
            }
          }
        },
        "deprecated" : false
      },
      "patch" : {
        "summary" : "Verify or reject loan",
        "description" : "verifys a loan, put the verify status into the request signupBody.\nNB: Request signupBody must be an encoded URL search param forexample: new URLSearchParam({ 'status': 'verified' }).",
        "operationId" : "VerifyALoan",
        "parameters" : [ {
          "name" : "Content-Type",
          "in" : "header",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "example" : "application/x-www-form-urlencoded"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/x-www-form-urlencoded" : {
              "schema" : {
                "$ref" : "#/components/schemas/approveLoanBody"
              }
            }
          },
          "required" : false
        },
        "responses" : {
          "200" : {
            "headers" : {
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "keep-alive"
                  }
                }
              },
              "Content-Length" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : 35
                  }
                }
              },
              "Content-Type" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "application/json; charset=utf-8"
                  }
                }
              },
              "date" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Mon, 29 Apr 2019 15:00:30 GMT"
                  }
                }
              },
              "x-powered-by" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Express"
                  }
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  
                },
                "example" : {
                  "status" : 200,
                  "message" : "approved"
                }
              }
            }
          }
        },
        "deprecated" : false
      }
    },
    "/users/manziroger@gmail.com/verify" : {
      "patch" : {
        "summary" : "Verify user",
        "description" : "Verify user by email ID, pasing it as a parameter in the URL",
        "operationId" : "VerifyAUser",
        "parameters" : [ {
          "name" : "Content-Type",
          "in" : "header",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "example" : "application/x-www-form-urlencoded"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/x-www-form-urlencoded" : {
              "schema" : {
                "$ref" : "#/components/schemas/verifyUserBody"
              }
            }
          },
          "required" : false
        },
        "responses" : {
          "202" : {
            "headers" : {
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "keep-alive"
                  }
                }
              },
              "Content-Length" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : 35
                  }
                }
              },
              "Content-Type" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "application/json; charset=utf-8"
                  }
                }
              },
              "date" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Mon, 29 Apr 2019 14:59:08 GMT"
                  }
                }
              },
              "x-powered-by" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Express"
                  }
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  
                },
                "example" : {
                  "status" : 202,
                  "message" : "verified"
                }
              }
            }
          }
        },
        "deprecated" : false
      }
    },
    "/loans/1/repayments" : {
      "get" : {
        "summary" : "Retrieve specific loan application",
        "description" : "Get Loan Repayment data by Id",
        "operationId" : "GetASpecificLoanRepayment",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "headers" : {
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "keep-alive"
                  }
                }
              },
              "Content-Length" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : 186
                  }
                }
              },
              "Content-Type" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "application/json; charset=utf-8"
                  }
                }
              },
              "date" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Mon, 29 Apr 2019 15:09:15 GMT"
                  }
                }
              },
              "x-powered-by" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Express"
                  }
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  
                },
                "example" : {
                  "status" : 200,
                  "data" : {
                    "id": 1,
                    "user": "manziroger@quickcredit.com",
                    "createdOn": "2019-04-11",
                    "status": "pending",
                    "repaid": false,
                    "tenor": 6,
                    "amount": 1200,
                    "paymentInstallment": 210,
                    "balance": 1050,
                    "Interest": 60
                }
                }
              }
            }
          }
        },
        "deprecated" : false
      },
      "post" : {
        "summary" : "Post loan repayment",
        "description" : "Post loan repayment by passing loan ID as a URL param.\nNB. ADMIN can use same endpoint to make a loan repayment transaction in favor of a user,  by passing in email ID of a user in the URL as param",
        "operationId" : "PostLoanRepayment",
        "parameters" : [ {
          "name" : "Content-Type",
          "in" : "header",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "example" : "application/x-www-form-urlencoded"
          }
        }],
        "requestBody" : {
          "content" : {
            "application/x-www-form-urlencoded" : {
              "schema" : {
                "$ref" : "#/components/schemas/postLoanRepaymentTransaction"
              }
            }
          },
          "required" : false
        },
        "responses" : {
          "201" : {
            "headers" : {
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "keep-alive"
                  }
                }
              },
              "Content-Length" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : 203
                  }
                }
              },
              "Content-Type" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "application/json; charset=utf-8"
                  }
                }
              },
              "date" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Mon, 29 Apr 2019 15:04:10 GMT"
                  }
                }
              },
              "etag" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "W/\"cb-ULixrawbCz1H8QOmI43E7Efm50I\""
                  }
                }
              },
              "x-powered-by" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Express"
                  }
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  
                },
                "example" : {
                  "status" : 201,
                  "Created" : true,
                  "data" :{
                    "id": 1,
                    "loanId": 1,
                    "amount": 1200,
                    "createdOn": "2019-04-11 12:45:11",
                    "interest": 60,
                    "monthlyInstallement": 210,
                    "paidAmount": 210,
                    "balance": 1050
                  }
                }
              }
            }
          }
        },
        "deprecated" : false
      }
    },
    "/users" : {
      "get" : {
        "summary" : "Retrieve all users",
        "description" : "Retrieves all users stored in the database",
        "operationId" : "GetAllUsers",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "headers" : {
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "keep-alive"
                  }
                }
              },
              "Content-Length" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : 308
                  }
                }
              },
              "Content-Type" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "application/json; charset=utf-8"
                  }
                }
              },
              "date" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Mon, 29 Apr 2019 15:17:04 GMT"
                  }
                }
              },
              "x-powered-by" : {
                "style" : "simple",
                "explode" : false,
                "content" : {
                  "text/plain" : {
                    "schema" : {
                      "type" : "string"
                    },
                    "example" : "Express"
                  }
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  
                },
                "example" : {
                  "status" : 200,
                  "data" : [ {
                    "id" : 1,
                    "token" : "fsgd7gdhdhg9ffds6d",
                    "firstName" : "Roger",
                    "lastName" : "Manzi",
                    "email" : "manziroger@gmail.com",
                    "password" : "123@abc",
                    "status" : "verified",
                    "isAdmin" : false,
                    "createdOn" : "Sat, 11 May 2019 09:59:49 GMT"
                  } ]
                }
              }
            }
          }
        },
        "deprecated" : false
      }
    }
  },
  "components" : {
    "schemas" : {
      "signupResponse" : {
        "title" : "signupResponse",
        "required" : [ "data", "status"],
        "type" : "object",
        "properties" : {
          "status" : {
            "type" : "integer",
            "format" : "int32"
          },
          "data" : {
            
          }
        },
        "example" : {
          "status" : 201,
          "data" : {
            "id" : 1,
            "firstName" : "Roger",
            "lastName" : "Manzi",
            "email" : "manziroger@gmail.com",
            "password" : "abc@123",
            "status" : "unverified",
            "isAdmin" : false,
            "createdOn" : "Sat, 11 May 2019 09:59:49 GMT"
          }
        }
      },
      "signupResponseData" : {
        "title" : "signupResponseData",
        "required" : [  "id","firstName", "lastName", "email", "password","isAdmin", "status", "createdOn" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int32"
          },
          "firstName" : {
            "type" : "string"
          },
          "lastName" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          },
          "status" : {
            "type" : "string"
          },
          "isAdmin" : {
            "type" : "boolean"
          },
          "createdOn" : {
            "type" : "string"
          }
        }
      },
      "signinResponse" : {
        "title" : "signinResponse",
        "required" : [  "data", "status" ],
        "type" : "object",
        "properties" : {
          "status" : {
            "type" : "integer",
            "format" : "int32"
          },
          "data" : {
            
          }
        },
        "example" : {
          "status" : 200,
          "data" : {
            "id" : 1,
            "token" : "dhfs8gdgd6d9scx0xz6sd",
            "firstName" : "Roger",
            "lastName" : "Manzi",
            "email" : "manziroger@gmail.com",
            "password" : "123@abc",
            "status" : "unverified",
            "isAdmin" : false,
            "createdOn" : "Sat, 11 May 2019 09:59:49 GMT"
          }
        }
      },
      "loanApplicationResponse" : {
        "title" : "loanApplicationResponse",
        "required" : [ "id", "user", "amount", "balance", "interest", "paymentInstallment", "repaid", "status", "tenor", "createdOn" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int32"
          },
          "user" : {
            "type" : "string"
          },
          "createdOn" : {
            "type" : "string"
          },
          "status" : {
            "type" : "string"
          },
          "tenor" : {
            "type" : "integer",
            "format" : "int32"
          },
          "amount" : {
            "type" : "integer",
            "format" : "int32"
          },
          "interest" : {
            "type" : "integer",
            "format" : "int32"
          },
          "repaid" : {
            "type" : "boolean"
          },
          "paymentInstallment" : {
            "type" : "integer",
            "format" : "int32"
          },
          "balance" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "retrieveLoanApplications" : {
        "title" : "retrieveLoanApplications",
        "required" : [ "data", "status" ],
        "type" : "object",
        "properties" : {
          "status" : {
            "type" : "integer",
            "format" : "int32"
          },
          "data" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/loanApplicationResponseData"
            }
          }
        },
        "example" : {
          "status" : 200,
          "data" : [ {
            "id" : 1,
            "user" : "manziroger@gmail.com",
            "status" : "pending",
            "tenor" : 6,
            "amount" : 1200,
            "interest" : 60,
            "repaid" : false,
            "paymentInstallment" : 210,
            "balance" : 1260,
            "createdOn" : "Mon, 29 Apr 2019 14:45:53 GMT"
            } ]
        }
      },
      "retrieveLoanApplicationsResponse" : {
        "title" : "retrieveLoanApplicationsResponse",
        "required" : [ "data", "status" ],
        "type" : "object",
        "properties" : {
          "status" : {
            "type" : "integer",
            "format" : "int32"
          },
          "data" : {
            "$ref" : "#/components/schemas/loanApplicationResponseDataData"
          }
        },
        "example" : {
          "status" : 200,
          "data" : {
            "id" : 1,
            "user" : "manziroger@gmail.com",
            "status" : "pending",
            "tenor": 6,
            "amount" : 1200,
            "interest" : 60,
            "repaid" : false,
            "paymentInstallment" : 210,
            "balance" : 1260,
            "createdOn" : "Mon, 29 Apr 2019 14:45:53 GMT"
          }
        }
      },
      "verifyUserResponse" : {
        "title" : "verifyUserResponse",
        "required" : [ "message", "status" ],
        "type" : "object",
        "properties" : {
          "status" : {
            "type" : "integer",
            "format" : "int32"
          },
          "message" : {
            "type" : "string"
          }
        },
        "example" : {
          "status" : 202,
          "message" : "verified"
        }
      },
      "approveLoanResponse" : {
        "title" : "approveLoanResponse",
        "required" : [ "message", "status" ],
        "type" : "object",
        "properties" : {
          "status" : {
            "type" : "integer",
            "format" : "int32"
          },
          "message" : {
            "type" : "string"
          }
        },
        "example" : {
          "status" : 200,
          "message" : "approved"
        }
      },
      "postLoanRepaymentTransactionResponse" : {
        "title" : "postLoanRepaymentTransactionResponse",
        "required" : [ "Created", "data", "status" ],
        "type" : "object",
        "properties" : {
          "status" : {
            "type" : "integer",
            "format" : "int32"
          },
          "Created" : {
            "type" : "string"
          },
          "data" : {
            "$ref" : "#/components/schemas/loanRepayTransactionResponseData"
          }
        },
        "example" : {
          "status" : 201,
          "Created" : true,
          "data" : {
            "id" : 1,
            "loanId" : 1,
            "createdOn" : "Mon, 29 Apr 2019 15:04:10 GMT",
            "amount" : 1200,
            "monthlyInstallment" : 210,
            "paidAmount" : 210,
            "balance" : 2700
          }
        }
      },
      "loanRepayTransactionResponse" : {
        "title" : "loanRepayTransactionResponse",
        "required" : [ "amount", "balance", "createdOn", "id", "loanId",  "monthlyInstallment", "paidAmount" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int32"
          },
          "loanId" : {
            "type" : "integer",
            "format" : "int32"
          },
          "createdOn" : {
            "type" : "string"
          },
          "amount" : {
            "type" : "integer",
            "format" : "int32"
          },
          "monthlyInstallment" : {
            "type" : "integer",
            "format" : "int32"
          },
          "paidAmount" : {
            "type" : "integer",
            "format" : "int32"
          },
          "balance" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "retrieveSpecificLoanResponse" : {
        "title" : "retrieveSpecificLoanResponse",
        "required" : [ "data", "status" ],
        "type" : "object",
        "properties" : {
          "status" : {
            "type" : "integer",
            "format" : "int32"
          },
          "data" : {
            "$ref" : "#/components/schemas/loanRepayTransactionResponseData"
          }
        },
        "example" : {
          "status" : 200,
          "data" : {
            "id" : 1,
            "user" : 1,
            "loanId" : 1,
            "createdOn" : "Mon, 29 Apr 2019 15:04:10 GMT",
            "amount" : 1200,
            "monthlyInstallment" : 210,
            "paidAmount" : 210,
            "balance" : 2700
          }
        }
      },
      "retrieveApprovedAndRepaidResponse" : {
        "title" : "retrieveApprovedAndRepaidResponse",
        "required" : [ "data", "status" ],
        "type" : "object",
        "properties" : {
          "status" : {
            "type" : "integer",
            "format" : "int32"
          },
          "data" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/loanApplicationResponseData"
            }
          }
        },
        "example" : {
          "status" : 200,
          "data" : [ {
            "id" : 1,
            "user" : "manziroger@gmail.com",
            "status" : "approved",
            "tenor": 6,
            "amount" : 1200,
            "interest" : 60,
            "repaid" : true,
            "paymentInstallment" : 210,
            "balance" : 0,
            "createdOn" : "Mon, 29 Apr 2019 14:45:53 GMT"
          } ]
        }
      },
      "retrieveApprovedAndNotRepaidResponse" : {
        "title" : "retrieveApprovedAndNotRepaidResponse",
        "required" : [ "data", "status" ],
        "type" : "object",
        "properties" : {
          "status" : {
            "type" : "integer",
            "format" : "int32"
          },
          "data" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/retrieveApprovedAndNotRepaidResponseData"
            }
          }
        },
        "example" : {
          "status" : 200,
          "data" : [ {
            "id" : 1,
            "user" : "manziroger@gmail.com",
            "status" : "approved",
            "tenor": 6,
            "amount" : 1200,
            "interest" : 60,
            "repaid" : false,
            "paymentInstallment" : 210,
            "createdOn" : "Mon, 29 Apr 2019 14:45:53 GMT"
            } ]
        }
      },
      "retrieveApprovedAndNotRepaidResponse" : {
        "title" : "retrieveApprovedAndNotRepaidResponse",
        "required" : [ "amount", "createdOn", "id", "interest", "paymentInstallment", "repaid", "status", "tenor", "user" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int32",
            "example" : 1
          },
          "user" : {
            "type" : "string",
            "example" : "manziroger@gmail.com"
          },
          "createdOn" : {
            "type" : "string",
            "example" : "Mon, 29 Apr 2019 14:45:53 GMT"
          },
          "status" : {
            "type" : "string",
            "example" : "approved"
          },
          "tenor" : {
            "type" : "integer",
            "format" : "int32",
            "example" : 4
          },
          "amount" : {
            "type" : "integer",
            "format" : "int32",
            "example" : 1200
          },
          "interest" : {
            "type" : "integer",
            "format" : "int32",
            "example" : 60
          },
          "repaid" : {
            "type" : "boolean",
            "example" : false
          },
          "paymentInstallment" : {
            "type" : "integer",
            "format" : "int32",
            "example" : 210
          }
        }
      },
      "retrieveAllUsersResponse" : {
        "title" : "retrieveAllUsersResponse",
        "required" : [ "data", "status" ],
        "type" : "object",
        "properties" : {
          "status" : {
            "type" : "integer",
            "format" : "int32"
          },
          "data" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/signupResponseData"
            }
          }
        },
        "example" : {
          "status" : 200,
          "data" : [ {
            "id" : 1,
            "token" : "adhs78gdg3css4sfsgf",
            "firstName" : "Roger",
            "lastName" : "Manzi",
            "email" : "manziroger@gmail.com",
            "password" : "abc@123",
            "status" : "verified",
            "isAdmin" : false,
            "createdOn" : "Sat, 11 May 2019 09:59:49 GMT"
          } ]
        }
      },
      "signupBody" : {
        "required" : [ "email", "firstName", "lastName", "password" ],
        "type" : "object",
        "properties" : {
          "firstName" : {
            "type" : "string",
            "example" : "manzi"
          },
          "lastName" : {
            "type" : "string",
            "example" : "roger"
          },
          "email" : {
            "type" : "string",
            "example" : "example@gmail.com"
          },
          "password" : {
            "type" : "string",
            "example" : "kigali"
          }
        }
      },
      "signinBody" : {
        "required" : [ "email", "password" ],
        "type" : "object",
        "properties" : {
          "email" : {
            "type" : "string",
            "example" : "mnzroger@gmail.com"
          },
          "password" : {
            "type" : "string",
            "example" : "abc@123"
          }
        }
      },
      "loanApplicationBody" : {
        "required" : [ "amount", "tenor" ],
        "type" : "object",
        "properties" : {
          "tenor" : {
            "type" : "string",
            "example" : "4"
          },
          "amount" : {
            "type" : "string",
            "example" : "4000"
          }
        }
      },
      "approveLoanBody" : {
        "required" : [ "status" ],
        "type" : "object",
        "properties" : {
          "status" : {
            "type" : "string",
            "example" : "approved"
          }
        }
      },
      "postLoanRepaymentTransaction" : {
        "required" : [ "amount" ],
        "type" : "object",
        "properties" : {
          "amount" : {
            "type" : "string",
            "example" : "1200"
          }
        }
      }
    }
  }
}